-- v170 : 발주서 메일 — 협력업체 이메일·담당자, 메일 발송 기록
alter table public.vendors add column if not exists email text;
alter table public.vendors add column if not exists contact_name text;

create table if not exists public.mail_log (
  id bigint generated by default as identity primary key,
  kind text, category text, vendor_name text, job_no text,
  to_addr text, subject text, sent_by text, lines int,
  created_at timestamptz default now()
);
alter table public.mail_log enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='mail_log' and policyname='mail_log_all') then
    create policy mail_log_all on public.mail_log for all to authenticated using (true) with check (true);
  end if;
end $$;

-- ────────────────────────────────────────────────────────────────
-- 메일 실제 발송은 Edge Function  mes-mail  이 합니다 (supabase/functions/mes-mail/index.ts).
-- 배포:  supabase functions deploy mes-mail --no-verify-jwt
-- 비밀:  supabase secrets set RESEND_API_KEY=re_xxx MAIL_FROM="IPTK MES <order@yourdomain.com>"
-- 함수가 없으면 화면은 자동으로 메일 앱(mailto)으로 열립니다.
-- ────────────────────────────────────────────────────────────────
